name: Deploy DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'airflow/dags/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy DAGs with .env
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          cat > ./airflow/dags/.env << EOF
          host=$DB_HOST
          port=$DB_PORT
          dbname=$DB_NAME
          dbuser=$DB_USER
          dbpassword=$DB_PASSWORD
          api_key=$WEATHER_API_KEY
          EOF
          
          sshpass -p "$PASSWORD" rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./airflow/dags/ $USER@$HOST:/home/and1m3n/weather_proj/airflow/dags/